### ISSUE TITLE
Game Gives Black Screen When Enabling MOD

### ISSUE THREAD

**Issue by rebelAlliance09** [Timberborn-Modding-Central/TimberAPI#27]
Hey there, When ever i enable TimberAPI my game goes into blackscreen it was working a few months ago and recently i came back and wanted to do modded again. but when i enable the mod it gives a blackscreen, i have tested it and it is only due to your mod. any help on what this could be?

**Comment by Mellinger1234** [comment]
Hey, I do have the same issue ever since I updated this mod a few days ago. But I have to add that I didn't use the mod for several weeks/month, and did not check if it is going to work before updating. I tried a combination of older versions, but ended either in a black game screen or the game without working mod. 

There are several warnings while loading in the BepInEx 5.4.19.0 terminal:

1. [Warning:   BepInEx] Plugin [TimberAPI 0.4.4] targets a wrong version of BepInEx (5.4.20.0) and might not work until you update
The latest version of BepInEx is 5.4.19.0, at least this is what the website says.

2. [Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly TimberAPI, Version=0.4.4.0, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not resolve type with token 01000046 from typeref (expected class 'Timberborn.Persistence.ISpecificationService' in assembly 'Timberborn.Persistence, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <6073cf49ed704e958b8a66d540dea948>:0
  at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0
System.TypeLoadException: Could not resolve type with token 01000046 from typeref (expected class 'Timberborn.Persistence.ISpecificationService' in assembly 'Timberborn.Persistence, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')

3. [Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000046 from typeref (expected class 'Timberborn.Persistence.ISpecificationService' in assembly 'Timberborn.Persistence, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')

Hopefully those warnings and error messages within the terminal are helpful.

**Comment by hytonhan** [comment]
Hello!
@rebelAlliance09 We would need more information to pin down the issue. Are you on stable or experimental? One common issue is that TimberAPI version v0.4.x only work on experimental. If you are on stable, downgrade TimberAPI to v0.3.2.

@Mellinger1234 Thx for the error logs. Judging by them my guess is that you on playing on the stable release with TimberAPI v0.4.4. Then the fix is to downgrade TimberAPI to v.0.3.2. TimberAPI version v0.4.x only work on experimental branch.

If these issues persist, please be in contact!

**Comment by GiantWod** [comment]
> @ Mellinger1234 Thx for the error logs. Judging by them my guess is that you on playing on the stable release with TimberAPI v0.4.4. Then the fix is to downgrade TimberAPI to v.0.3.2. TimberAPI version v0.4.x only work on experimental branch.

I just want to add that after downgrading the issue was fixed, thanks, even though im not OP

**Comment by Mellinger1234** [comment]
> @Mellinger1234 Thx for the error logs. Judging by them my guess is that you on playing on the stable release with TimberAPI v0.4.4. Then the fix is to downgrade TimberAPI to v.0.3.2. TimberAPI version v0.4.x only work on experimental branch.
> 
> If these issues persist, please be in contact!

@hytonhan : Thanks, this works just fine. Issue fixed.
