### ISSUE TITLE
Add exceptions/errors to in game notifcations

### ISSUE THREAD

**Issue by awsdert** [Timberborn-Modding-Central/TimberAPI#82]
Like the "Beaver is starving"/"Beaver is thirsty" mods could you add the exceptions/errors that are not handled to the in-game notifications (assuming they happen during gameplay) please? Can just add an option to the menu to make them pop up, when the option is enabled can just do the default of ignoring it or whatever. Reason I ask is because it would be easier than constantly switching in & out of TB to look at the console to see what occurred. I'm not a mod creator but I imagine existing ones would find it helpful to have notifications in game where they would notice them whilst testing their mods. As for players like myself it would be easier to see where conflicts are occurring.

**Comment by KYPremco** [comment]
I am still unsure what this mean. If the game throws an exception it will most likely crash instead of being able to continue, so then you cannot see a notification like "Beaver is starving". That aside an execption, even just the message, would never fit in such small box?

If it's something like "Train can't find path" or something, that is something the modder already can add if they want to.

**Comment by awsdert** [comment]
Not the exceptions I've seen in the console/terminal, it's those exceptions I want to be able to see in notifications, ones that crash the entire app would be caught with a debugger which is beyond the scope of this feature request

**Comment by KYPremco** [comment]
Can you give any examples of your definition on "exceptions/errors" and screenshots on what you want to transfer to them.
